apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  postgres-db: {{ .Values.secrets.postgresDb | b64enc | quote }}
  postgres-user: {{ .Values.secrets.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  rabbitmq-user: {{ .Values.secrets.rabbitmqUser | b64enc | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | b64enc | quote }}
